import {registerWebMCPTools,createSolanaWebMCPTools} from '../../src/webmcp/index.ts';
import {WebMCP} from '../../WebMCP-main 3/src/webmcp.js';
import {validateSwap} from './server/solana.mjs';
const $=id=>document.getElementById(id);
let config,accessToken='',wallet=null,remote=null,crawlId=null,cursor=null,legacy=null;
const network=()=>$('network').value;
function log(message){const li=document.createElement('li');li.textContent=`${new Date().toLocaleTimeString()}  ${message}`;$('activity-log').prepend(li);while($('activity-log').children.length>30)$('activity-log').lastChild.remove();}
function notice(message){$('notice').textContent=message;$('notice').hidden=false;log(message);}
function show(id,data){$(id).textContent=typeof data==='string'?data:JSON.stringify(data,null,2);}
function action(fn){return async event=>{event?.preventDefault();const target=event?.currentTarget;try{if(target?.tagName==='BUTTON')target.disabled=true;await fn(event);}catch(e){notice(e.message);}finally{if(target?.tagName==='BUTTON')target.disabled=false;}};}
async function api(path,body){
  const r=await fetch('/api/'+path,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':config?.csrf||'',...(accessToken?{authorization:`Bearer ${accessToken}`}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(70000)});
  const data=await r.json();if(!r.ok)throw new Error(data.error||`Request failed: ${r.status}`);return data.result;
}
function tab(name){document.querySelectorAll('.tab-panel').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-tab]').forEach(el=>{el.classList.toggle('active',el.dataset.tab===name);el.setAttribute('aria-current',el.dataset.tab===name?'page':'false');});}
for(const el of document.querySelectorAll('[data-tab]'))el.onclick=()=>tab(el.dataset.tab);
async function refreshNetwork(){
  const selected=network();$('chain-state').textContent='Refreshing…';
  try{const data=await api('solana/network',{network:selected});if(selected!==network())return data;$('slot').textContent=Number(data.slot).toLocaleString();$('chain-state').textContent=`Live · ${new Date(data.observedAt).toLocaleTimeString()}`;return data;}
  catch(e){if(selected===network()){$('chain-state').textContent='Unavailable · '+e.message;$('slot').textContent='—';}throw e;}
}
async function walletContext(){
  if(!wallet)return {connected:false,network:network(),publicKey:null};
  const result=await api('solana/wallet',{publicKey:wallet,network:network()});$('wallet-balance').textContent=`${result.solBalance.toLocaleString()} SOL · ${network()}`;return {...result,address:result.publicKey,connected:true};
}
async function resolveToken(query){
  const result=await api('solana/resolve',{query});$('tokens').replaceChildren();$('market').hidden=true;
  if(!result.length){const p=document.createElement('p');p.textContent='No Solana token candidates found.';$('tokens').append(p);}
  for(const t of result){const card=document.createElement('div');card.className='token-card';const icon=document.createElement('div');icon.className='token-icon';icon.textContent=(t.symbol||'?').slice(0,2);const info=document.createElement('div');const name=document.createElement('b');name.textContent=`${t.name} · ${t.symbol}`;const mint=document.createElement('code');mint.textContent=t.mint;const button=document.createElement('button');button.textContent='Inspect ↗';button.onclick=action(()=>market(t.mint));info.append(name,mint);card.append(icon,info,button);$('tokens').append(card);}
  log(`Resolved ${query}: ${result.length} candidate(s).`);return result;
}
async function market(mint){const data=await api('solana/market',{mint});$('market').hidden=false;$('market').replaceChildren();const pre=document.createElement('pre');pre.textContent=JSON.stringify(data.pair?{mint,pool:data.pair.pairAddress,dex:data.pair.dexId,priceUsd:data.pair.priceUsd,liquidityUsd:data.pair.liquidity.usd,source:data.source,observedAt:data.observedAt}:{mint,status:'No liquid base-token pool found',source:data.source,observedAt:data.observedAt},null,2);$('market').append(pre);return data;}
function swapInput(){return {inputMint:$('input-mint').value.trim(),outputMint:$('output-mint').value.trim(),amount:$('amount').value.trim(),slippageBps:Number($('slippage').value),swapMode:'ExactIn'};}
function stageSwap(input){validateSwap(input);if(network()!=='mainnet-beta')throw new Error('Swap staging uses mainnet token identities; select Mainnet Beta');const ticketId=crypto.randomUUID();const ticket={id:ticketId,ticketId,staged:true,requiresUserSignature:true,summary:'Swap prepared for human review; no transaction created',status:'awaiting-human-review',network:network(),...input,createdAt:new Date().toISOString(),signed:false,broadcast:false};$('input-mint').value=input.inputMint;$('output-mint').value=input.outputMint;$('amount').value=input.amount;$('slippage').value=input.slippageBps;$('ticket').hidden=false;show('ticket-data',ticket);tab('explore');log('Swap ticket staged for human review. No transaction submitted.');return ticket;}
const tools=createSolanaWebMCPTools({getWalletContext:walletContext,resolveToken,getSwapQuote:input=>api('solana/quote',{...input,network:network()}),stageSwap,inspectTransaction:signature=>api('solana/inspect',{signature,network:network()})});
tools.push({name:'solana.get_network_status',description:'Read the selected Solana network, confirmed slot, and node version from live RPC.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:refreshNetwork},{name:'solana.get_token_market',description:'Read the highest-liquidity Solana pool where the exact mint is the base token. Includes source and timestamp.',inputSchema:{type:'object',properties:{mint:{type:'string'}},required:['mint'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:({mint})=>market(mint)});
function validateArgs(tool,args){if(!args||typeof args!=='object'||Array.isArray(args))throw new Error('Tool arguments must be an object');const schema=tool.inputSchema||{};for(const key of schema.required||[])if(!(key in args))throw new Error(`Missing ${key}`);if(schema.additionalProperties===false)for(const key of Object.keys(args))if(!(key in (schema.properties||{})))throw new Error(`Unknown argument: ${key}`);}
const inspection=tools.find(t=>t.name==='solana.inspect_transaction');
inspection.description='Read a confirmed Solana transaction by signature, including parsed instructions and metadata. Does not accept serialized transactions or sign anything.';
const catalog=tools.map(tool=>({...tool,execute:async(args={})=>{validateArgs(tool,args);const result=await tool.execute(args,{signal:new AbortController().signal});log(`Tool completed: ${tool.name}`);return result;}}));
window.solanaWebMCP=Object.freeze({mode:()=>document.modelContext?'document':navigator.modelContext?'navigator':'application-fallback',listTools:()=>catalog.map(({execute,...t})=>t),executeTool:async(name,args={})=>{const tool=catalog.find(t=>t.name===name);if(!tool)throw new Error('Unknown Solana tool');return tool.execute(args);}});
// This application fallback does not install or impersonate browser-owned APIs.
const nativeTools=catalog.map(t=>({...t,execute:async(args)=>({content:[{type:'text',text:JSON.stringify(await t.execute(args))}]})}));
let dispose=()=>{};
try{dispose=await registerWebMCPTools(nativeTools);}catch(e){notice(`Native registration failed: ${e.message}`);}
window.addEventListener('pagehide',()=>dispose(),{once:true});
const mode=window.solanaWebMCP.mode();$('native-status').textContent=mode==='application-fallback'?'APP TOOLS READY':'NATIVE WEBMCP';$('api-description').textContent=mode==='application-fallback'?'This browser does not expose native WebMCP. These tools work through the application API and optional legacy bridge. Use a compatible browser or Cloudflare lab for native discovery.':`Registered through ${mode}.modelContext. The same tools update this visible workspace.`;$('tool-count').textContent=catalog.length;
for(const tool of catalog){const card=document.createElement('div');card.className='tool-card';const title=document.createElement('b');title.textContent=tool.name;const p=document.createElement('p');p.textContent=tool.description;card.append(title,p);$('tool-list').append(card);const option=document.createElement('option');option.value=tool.name;option.textContent=tool.name;$('local-tool').append(option);}
$('local-tool').onchange=()=>{const t=catalog.find(t=>t.name===$('local-tool').value);show('tool-output',t.inputSchema);$('local-args').value=JSON.stringify(t.name==='solana.resolve_token'?{query:'SOL'}:t.name==='solana.get_token_market'?{mint:$('input-mint').value}:t.name.includes('swap')?swapInput():{},null,2);};
$('execute-local').onclick=action(async()=>show('tool-output',await window.solanaWebMCP.executeTool($('local-tool').value,JSON.parse($('local-args').value))));
$('token-form').onsubmit=event=>{event.preventDefault();const result=resolveToken($('token-query').value.trim());event.respondWith?.(result.then(JSON.stringify));result.catch(e=>notice(e.message));};
$('swap-form').onsubmit=action(()=>stageSwap(swapInput()));
$('quote').onclick=action(async()=>{const result=await api('solana/quote',{...swapInput(),network:network()});$('ticket').hidden=false;show('ticket-data',result);$('quote-state').textContent=`Quote received ${result.observedAt}; request a fresh quote before execution.`;});
$('dismiss-ticket').onclick=()=>{$('ticket').hidden=true;show('ticket-data','');log('Review ticket dismissed.');};
$('network').onchange=action(async()=>{$('ticket').hidden=true;$('wallet-balance').textContent=wallet?'Refreshing balance…':'Connect to read your balance';await refreshNetwork();if(wallet)await walletContext();});
$('connect-wallet').onclick=action(async()=>{const provider=window.phantom?.solana||window.solana;if(!provider?.connect)throw new Error('Open this page in a browser with a Solana wallet extension, such as Phantom.');const result=await provider.connect();wallet=result.publicKey.toString();$('wallet-address').textContent=`${wallet.slice(0,5)}…${wallet.slice(-5)}`;$('connect-wallet').textContent='Wallet connected';await walletContext();provider.on?.('disconnect',()=>{wallet=null;$('wallet-address').textContent='Not connected';$('wallet-balance').textContent='Connect to read your balance';});provider.on?.('accountChanged',key=>{wallet=key?.toString()||null;$('wallet-address').textContent=wallet?`${wallet.slice(0,5)}…${wallet.slice(-5)}`:'Not connected';$('wallet-balance').textContent='Balance needs refresh';});});
$('enable-legacy').onclick=action(()=>{if(legacy)return;legacy=new WebMCP({color:'#c4f779'});for(const t of catalog)legacy.registerTool(t.name,t.description,t.inputSchema,async args=>({content:[{type:'text',text:JSON.stringify(await t.execute(args))}]}));legacy.registerResource('solana-context','Current Solana network and connected public wallet',{uri:'solana://context',mimeType:'application/json'},async()=>({contents:[{uri:'solana://context',mimeType:'application/json',text:JSON.stringify(await walletContext())}]}));legacy.registerPrompt('research-solana-token','Research a Solana token without submitting a transaction',[{name:'mint',description:'Exact mint address',required:true}],async({mint})=>({messages:[{role:'user',content:{type:'text',text:`Inspect Solana mint ${mint}. Verify the mint and source timestamps. Present findings for human review.`}}]}));log('Legacy bridge enabled. Use its widget to connect with a one-use token.');});
function remoteTools(data){$('remote-tool').replaceChildren();for(const t of data.tools||[]){const o=document.createElement('option');o.value=t.name;o.textContent=t.name;$('remote-tool').append(o);}$('execute-remote').disabled=!(data.tools||[]).length;show('browser-output',data);}
function view(url){$('live-view').hidden=!url;if(url){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.hostname!=='live.browser.run')throw new Error('Unexpected Live View URL');$('live-view').href=url;}}
$('start-browser').onclick=action(async()=>{if(remote)throw new Error('End the current session first');remote=await api('browser/start',{url:$('browser-url').value});$('session-controls').hidden=false;$('close-browser').disabled=false;view(remote.liveView);remoteTools(remote);log(`Remote Solana browser started: ${remote.url}`);});
$('close-browser').onclick=action(async()=>{if(remote)await api('browser/action',{id:remote.id,action:'close'});remote=null;$('session-controls').hidden=true;view(null);show('browser-output','Session closed.');});
$('remote-tools').onclick=action(async()=>remoteTools(await api('browser/action',{id:remote.id,action:'tools'})));
$('execute-remote').onclick=action(async()=>{const result=await api('browser/action',{id:remote.id,action:'execute',name:$('remote-tool').value,arguments:JSON.parse($('remote-args').value)});remoteTools(result.discovery);show('browser-output',result);});
function capture(data){$('capture-image').hidden=true;if(data?.base64&&data.contentType?.startsWith('image/')){$('capture-image').src=`data:${data.contentType};base64,${data.base64}`;$('capture-image').hidden=false;show('capture-output','Screenshot captured.');}else show('capture-output',data);}
$('remote-screenshot').onclick=action(async()=>capture(await api('browser/action',{id:remote.id,action:'screenshot'})));
$('handoff').onclick=action(async()=>{const data=await api('browser/action',{id:remote.id,action:'handoff',instructions:$('handoff-instructions').value});view(data.liveView);show('browser-output',data);});
$('handoff-state').onclick=action(async()=>show('browser-output',await api('browser/action',{id:remote.id,action:'handoff-state'})));
for(const button of document.querySelectorAll('[data-quick]'))button.onclick=action(async()=>{const kind=button.dataset.quick;const data=await api('browser/quick',{action:kind,url:$('browser-url').value,prompt:$('extract-prompt').value,fontCss:$('font-css').value,limit:3});capture(data);if(kind==='crawl'){crawlId=typeof data==='string'?data:data.id;cursor=null;$('crawl-controls').hidden=false;}});
async function crawlStatus(next=false){const data=await api('browser/crawl',{id:crawlId,...(next&&cursor!==null?{cursor}:{})});cursor=data.cursor??null;$('crawl-next').disabled=cursor===null;capture(data);}
$('crawl-status').onclick=action(()=>crawlStatus());$('crawl-next').onclick=action(()=>crawlStatus(true));$('crawl-cancel').onclick=action(async()=>capture(await api('browser/crawl',{id:crawlId,cancel:true})));
$('clear-log').onclick=()=>$('activity-log').replaceChildren();
async function init(){const response=await fetch('/api/config',{headers:accessToken?{authorization:`Bearer ${accessToken}`}:{}});if(response.status===401){$('access-form').hidden=false;throw new Error('An application access token is required');}if(!response.ok)throw new Error('Failed to load browser configuration');config=await response.json();$('access-form').hidden=true;$('cloud-state').textContent=config.browser.configured?'Cloudflare is configured. Start a lab session to discover native page tools.':'Cloudflare is not configured. Set the account ID and Browser Rendering API token on the server to enable remote runs.';$('quote-state').textContent=config.quoteConfigured?'Live Jupiter quotes available.':'Live quotes need JUPITER_API_KEY on the server. Swap staging is available.';for(const url of config.browser.sites){if([...$('browser-url').options].some(o=>o.value===url))continue;const o=document.createElement('option');o.textContent=url;$('browser-url').append(o);}await refreshNetwork();}
$('access-form').onsubmit=action(async()=>{accessToken=$('access-token').value;$('access-token').value='';await init();});
await init().catch(e=>notice(e.message));
setInterval(()=>{if(config&&document.visibilityState==='visible')refreshNetwork().catch(()=>{});},30000);
